### ISSUE TITLE
Needs a logo

### ISSUE THREAD

**Issue by thomas-reimonn** [abdenlab/oxbow#62]
Gotta have a cool logo for powerpoints and such

**Comment by nvictus** [comment]
Actually, we have a nice one for oxbow!

![image](https://github.com/abdenlab/oxbow/assets/1270651/a560047a-a7c0-4dfa-84f7-e9c8b2f526b5)

![image](https://github.com/abdenlab/oxbow/assets/1270651/5abe9e55-cd1c-43b5-a22f-8b15e96a9143)
